name: build.yml
# 触发脚本的条件，main分支push代码的时候
on:
  push:
    branches:
      - main
# 要执行的任务
jobs:
  # 任务名称
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境（必填） self-hosted, linux  ubuntu-latest
    runs-on: ubuntu-latest
    name: build
    # 任务步骤
    steps:
      # 获取源码
      - name: checkout Code
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@v2
      # 安装node
      - name: add node.js
        # 使用action库 actions/setup-node 安装node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      # 安装依赖
      - name: npm install
        run: npm install
        #working-directory: "../working"
      # 打包
      - name: npm run build
        run: npm run build
        #working-directory: "../working"
